/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_luiscastro;

import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lfern
 */
public class ProductoGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProductoGUI
     */
    public ProductoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_archivos = new javax.swing.JPopupMenu();
        jmi_LoadF = new javax.swing.JMenuItem();
        jmiPP_refresh = new javax.swing.JMenuItem();
        pp_table = new javax.swing.JPopupMenu();
        jmipp_clear = new javax.swing.JMenuItem();
        tf_commands = new javax.swing.JTextField();
        btn_commands = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_archivos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_productos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        m_file = new javax.swing.JMenu();
        jmi_newFile = new javax.swing.JMenuItem();
        jmi_ImportFile = new javax.swing.JMenuItem();
        m_window = new javax.swing.JMenu();
        m_clear = new javax.swing.JMenu();
        jmi_clearCMDL = new javax.swing.JMenuItem();
        jmi_clearTable = new javax.swing.JMenuItem();
        jmi_refreshTree = new javax.swing.JMenuItem();
        m_help = new javax.swing.JMenu();
        jmi_ProductS = new javax.swing.JMenuItem();
        jmi_Commands = new javax.swing.JMenuItem();

        jmi_LoadF.setText("Load Files");
        pp_archivos.add(jmi_LoadF);

        jmiPP_refresh.setText("Refresh Tree");
        pp_archivos.add(jmiPP_refresh);

        jmipp_clear.setText("Clear Table");
        pp_table.add(jmipp_clear);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_commands.setText("Entrar");
        btn_commands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_commandsMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Archivos CVS");
        jt_archivos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_archivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_archivos);

        jtable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Categoria", "Price", "Aisle", "Bin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_productos);

        m_file.setText("File");

        jmi_newFile.setText("New File");
        m_file.add(jmi_newFile);

        jmi_ImportFile.setText("Import File");
        m_file.add(jmi_ImportFile);

        jMenuBar1.add(m_file);

        m_window.setText("Window");

        m_clear.setText("Clear");

        jmi_clearCMDL.setText("Clear Command Line");
        m_clear.add(jmi_clearCMDL);

        jmi_clearTable.setText("Clear Table");
        m_clear.add(jmi_clearTable);

        m_window.add(m_clear);

        jmi_refreshTree.setText("Refresh Tree");
        m_window.add(jmi_refreshTree);

        jMenuBar1.add(m_window);

        m_help.setText("Help");

        jmi_ProductS.setText("Product Structure");
        m_help.add(jmi_ProductS);

        jmi_Commands.setText("Commands");
        m_help.add(jmi_Commands);

        jMenuBar1.add(m_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tf_commands, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_commands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_commands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_commands))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_archivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_archivosMouseClicked
        // TODO add your handling code here:
       if(evt.getButton()==3){
           pp_archivos.show(evt.getComponent(), evt.getX(), evt.getY());
       }
    }//GEN-LAST:event_jt_archivosMouseClicked

    private void jtable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_productosMouseClicked
        // TODO add your handling code here:
        if(evt.getButton() == 3){
            pp_table.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtable_productosMouseClicked

    private void btn_commandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_commandsMouseClicked
        // TODO add your handling code here:
        String comando = tf_commands.getText();
        String nom_archivo = "";
        boolean vcomando= false;
        if(comando.contains("./load")){
            nom_archivo = obtenerNombreArchivo(comando, nom_archivo);
            AdmProducto am = new AdmProducto(nom_archivo+".txt");
            if (am.archivo.exists()) {
                am.cargarArchivo();
                DefaultTableModel m = (DefaultTableModel)jtable_productos.getModel();
                m.setRowCount(0);
                for (Producto p : am.getProductos()) {
                    System.out.println(p);
                    Object[]row = {p.getId(),
                        p.getNombre(),
                        p.getCategory(),
                        p.getPrecio(),
                        p.getAisle(),
                        p.getBin()};                   
                m.addRow(row);
                }
                
                jtable_productos.setModel(m);
            }else{
                JOptionPane.showMessageDialog(this, "El archivo no existe!");
            }
                
        }else if(comando.contains("./create")){
            nom_archivo = obtenerNombreArchivo(comando, nom_archivo);
            
            
        }else if(comando.contains("./clear")){
            if((vcomando = validarComando(comando) == false)){
                JOptionPane.showMessageDialog(this, "Comando invalido!");
            }
        }else if(comando.contains("./refresh")){
            if((vcomando = validarComando(comando))== false){
                JOptionPane.showMessageDialog(this, "Comando invalido!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Comando invalido!");
        }
        tf_commands.setText("");
    }//GEN-LAST:event_btn_commandsMouseClicked
    
   
    public String obtenerNombreArchivo(String comando, String nom_archivo){
        Scanner sc = new Scanner(comando);
        sc.useDelimiter(" ");
        while (sc.hasNext()) {
                sc.next();
                nom_archivo = sc.next();   
            }
       return nom_archivo;
    }
    public boolean validarComando(String comando){
        Scanner sc = new Scanner(comando);
        sc.useDelimiter(" ");
        if(sc.hasNext()){
            return false;
        }else{
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_commands;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jmiPP_refresh;
    private javax.swing.JMenuItem jmi_Commands;
    private javax.swing.JMenuItem jmi_ImportFile;
    private javax.swing.JMenuItem jmi_LoadF;
    private javax.swing.JMenuItem jmi_ProductS;
    private javax.swing.JMenuItem jmi_clearCMDL;
    private javax.swing.JMenuItem jmi_clearTable;
    private javax.swing.JMenuItem jmi_newFile;
    private javax.swing.JMenuItem jmi_refreshTree;
    private javax.swing.JMenuItem jmipp_clear;
    private javax.swing.JTree jt_archivos;
    private javax.swing.JTable jtable_productos;
    private javax.swing.JMenu m_clear;
    private javax.swing.JMenu m_file;
    private javax.swing.JMenu m_help;
    private javax.swing.JMenu m_window;
    private javax.swing.JPopupMenu pp_archivos;
    private javax.swing.JPopupMenu pp_table;
    private javax.swing.JTextField tf_commands;
    // End of variables declaration//GEN-END:variables
}
